hmrc/pla-dynamic-stub

- app/uk/gov/hmrc/pla/stub/model/Protections.scala
Rename protections list field to match actual HOD API field name
> Fixed field name of protections list

- app/uk/gov/hmrc/pla/stub/controllers/PLAStubController.scala
- app/uk/gov/hmrc/pla/stub/model/PSALookupErrorResult.scala
- app/uk/gov/hmrc/pla/stub/model/PSALookupUpdatedResult.scala
- conf/app.routes
- test/uk/gov/hmrc/pla/stub/controllers/ControllerSpec.scala
Reverts hmrc/pla-dynamic-stub#46
> Revert "Removed psa lookup method within stub controller"

- app/uk/gov/hmrc/pla/stub/model/CreateLTAProtectionRequest.scala
- app/uk/gov/hmrc/pla/stub/services/PLAProtectionService.scala
Added certificationDate, protectedAmount, protectionReference to CreateLTAProtectionRequest
> Added certificationDate, protectedAmount, protectionReference

- app/uk/gov/hmrc/pla/stub/Generator.scala
- app/uk/gov/hmrc/pla/stub/model/CreateLTAProtectionRequest.scala
- app/uk/gov/hmrc/pla/stub/services/PLAProtectionService.scala
Reverts hmrc/pla-dynamic-stub#55
> Revert "Pla 1628 refactor spike"

- app/uk/gov/hmrc/pla/stub/model/CreateLTAProtectionRequest.scala
Reverts hmrc/pla-dynamic-stub#54
> Revert "protectionReference added as Optional"

- app/uk/gov/hmrc/pla/stub/model/CreateLTAProtectionRequest.scala
- app/uk/gov/hmrc/pla/stub/services/PLAProtectionService.scala
Reverts hmrc/pla-dynamic-stub#53
> Revert "Added certificationDate, protectedAmount, protectionReference"

- app/uk/gov/hmrc/pla/stub/Generator.scala
- app/uk/gov/hmrc/pla/stub/controllers/PLAStubController.scala
- app/uk/gov/hmrc/pla/stub/model/CreateLTAProtectionRequest.scala
- app/uk/gov/hmrc/pla/stub/model/EnumUtils.scala
- app/uk/gov/hmrc/pla/stub/model/Protection.scala
- app/uk/gov/hmrc/pla/stub/model/UpdateLTAProtectionRequest.scala
- app/uk/gov/hmrc/pla/stub/model/Version.scala
- app/uk/gov/hmrc/pla/stub/services/PLAProtectionService.scala
- conf/app.routes
- project/StubServiceBuild.scala
- test/uk/gov/hmrc/pla/stub/controllers/ControllerSpec.scala
- test/uk/gov/hmrc/pla/stub/controllers/controllers.scala
- test/uk/gov/hmrc/pla/stub/model/ModelSpec.scala
Reverts hmrc/pla-dynamic-stub#59
> Revert "Revert "Pla 1628 refactor spike""

- app/uk/gov/hmrc/pla/stub/model/CreateLTAProtectionRequest.scala
- app/uk/gov/hmrc/pla/stub/services/PLAProtectionService.scala
Reverts hmrc/pla-dynamic-stub#58
> Revert "Revert "Added certificationDate, protectedAmount, protectionReference""

- app/uk/gov/hmrc/pla/stub/model/CreateLTAProtectionRequest.scala
Reverts hmrc/pla-dynamic-stub#57
> Revert "Revert "protectionReference added as Optional""

- project/MicroService.scala
- project/StubServiceBuild.scala
- project/plugins.sbt
**Update** 
Updated Bootstrap and sbt auto-build as all the other updates had been done as part of story DL-1065.
> DL-1091 Updated Bootstrap and sbt-auto-build

- project/MicroService.scala
- project/StubServiceBuild.scala
- project/plugins.sbt
> New build migration

- project/StubServiceBuild.scala
- project/plugins.sbt
**Dependency uplift**
* Uplifted dependencies for `pla-dynamic-stub`
> DL-PLADS-dep-uplift Uplifted dependencies

- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
> DL-3587 Updating dependencies

- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/uk/gov/hmrc/pla/stub/controllers/ControllerSpec.scala
- test/uk/gov/hmrc/pla/stub/model/ModelSpec.scala
- test/uk/gov/hmrc/pla/stub/rules/RulesSpec.scala
> DL-5777 Play 2.8 upgrade

- app/uk/gov/hmrc/pla/stub/actions/ExceptionTriggersActions.scala
- app/uk/gov/hmrc/pla/stub/controllers/testControllers/TestSetupController.scala
- app/uk/gov/hmrc/pla/stub/guice/GuiceModuleLoader.scala
- app/uk/gov/hmrc/pla/stub/repository/MongoExceptionTriggerRepository.scala
- app/uk/gov/hmrc/pla/stub/repository/MongoProtectionRepository.scala
- app/uk/gov/hmrc/pla/stub/services/PLAProtectionService.scala
- conf/application.conf
- project/AppDependencies.scala
- test/uk/gov/hmrc/pla/stub/controllers/ControllerSpec.scala
> DL-9028 - Changed reactivemongo to hmrc-mongo

- .gitignore
- app/uk/gov/hmrc/pla/stub/controllers/PLAStubController.scala
**Bug fix / New feature** (delete as appropriate)
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
> DL-12905 added test data for new protection types

- project/AppDependencies.scala
- project/plugins.sbt
> DL-15082:Dependency Upgrade

- project/AppDependencies.scala
DL-15295:Rectifying bobby violation
> DL-15295:Rectifying bobby violation

- app/uk/gov/hmrc/pla/stub/controllers/HIPController.scala
- app/uk/gov/hmrc/pla/stub/model/hip/HIPProtectionsModel.scala
- app/uk/gov/hmrc/pla/stub/model/hip/ProtectionStatus.scala
- app/uk/gov/hmrc/pla/stub/model/hip/ProtectionType.scala
- app/uk/gov/hmrc/pla/stub/services/PLAProtectionService.scala
- app/uk/gov/hmrc/pla/stub/utils/Enumerable.scala
- build.sbt
- conf/app.routes
- conf/application.conf
- export-versions-for-it-tests
- project/AppDependencies.scala
- project/plugins.sbt
- test/uk/gov/hmrc/pla/stub/controllers/HIPControllerSpec.scala
**Bug fix / New feature** (delete as appropriate)
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
> DL-16704 | Initial set-up of HIP endpoints and data transformation

- app/uk/gov/hmrc/pla/stub/controllers/HIPController.scala
- app/uk/gov/hmrc/pla/stub/model/hip/HipNotification.scala
- app/uk/gov/hmrc/pla/stub/model/hip/ProtectionType.scala
- app/uk/gov/hmrc/pla/stub/rules/HipAmendmentRules.scala
- conf/application.conf
- test/uk/gov/hmrc/pla/stub/controllers/HIPControllerSpec.scala
- test/uk/gov/hmrc/pla/stub/controllers/controllers.scala
- test/uk/gov/hmrc/pla/stub/rules/HipAmendmentRulesSpec.scala
- test/uk/gov/hmrc/pla/stub/testdata/RandomNinoGenerator.scala
Big thanks to @Eoghan-Spillane-Accenture for providing `HipAmendmentRules` implementation.
> Make HIP amend endpoint return notification IDs from 1-14 range

- conf/testOnlyDoNotUseInAppConf.routes
**Bug fix / New feature** (delete as appropriate)
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
> DL-1742 Fix perf test 404 on staging
